name: Test AWS Credentials

on:
  workflow_dispatch:  # Manual trigger only

env:
  AWS_REGION: us-east-1

jobs:
  test-credentials:
    name: Test AWS Credentials
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      run: |
        echo "Setting AWS credentials from environment variables..."
        export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
        export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        export AWS_DEFAULT_REGION="${{ env.AWS_REGION }}"
        echo "Credentials set successfully"

    - name: Debug AWS credentials
      run: |
        echo "🔍 Debugging AWS credentials..."
        echo "AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
        echo "AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
        echo "AWS_REGION: $AWS_REGION"
        echo ""
        echo "Testing AWS connection..."
        aws sts get-caller-identity
        echo ""
        echo "✅ AWS credentials are working correctly!"

    - name: Test ECR access
      run: |
        echo "🔍 Testing ECR access..."
        aws ecr describe-repositories --region us-east-1 || echo "ECR repositories don't exist yet (this is normal for first deployment)"
        echo "✅ ECR access test completed"
